#!/bin/bash
# EcoBuilding — disaster-recovery backup (run ON the VM, e.g. via cron).
# Backs up the STATEFUL, IRREPLACEABLE data:
#   - Keycloak Postgres (user accounts / organizations)   -> pg_dump
#   - leads.jsonl (sales pipeline)                         -> copy
#   - grafana DB (dashboards, admin)                       -> volume tar
# Application data (BDNB/BAN/Géorisques) is public open data — NOT backed up
# (re-fetchable). Secrets.env is NOT backed up here (would defeat encryption);
# it is regenerated by deploy.sh and must be kept by the operator out-of-band.
#
# Output: /home/debian/backups/ecobuilding-YYYYMMDD-HHMMSS.tar.gz.age
# Encrypted at rest with age (recipient from ~/.config/ecobuilding/backup.pub).
# Retention: keep last 14 local archives. Off-site copy = operator's job
# (see SECURITY.md — a single-VM backup is not a real DR until copied off-box).
set -eu

STAMP=$(date +%Y%m%d-%H%M%S)
DIR=/home/debian/backups
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT
mkdir -p "$DIR"

echo "== keycloak postgres dump"
podman exec ecobuilding-auth_kc-db_1 pg_dump -U keycloak keycloak > "$WORK/keycloak.sql"

echo "== leads"
cp -f ~/projects/ecobuilding/data/leads/leads.jsonl "$WORK/leads.jsonl" 2>/dev/null || echo "(no leads yet)"

echo "== grafana volume"
podman run --rm -v ecobuilding-monitoring_grafana_data:/v:ro -v "$WORK":/out \
  docker.io/library/busybox tar czf /out/grafana.tar.gz -C /v . 2>/dev/null || echo "(grafana volume absent)"

TAR="$DIR/ecobuilding-$STAMP.tar.gz"
tar czf "$TAR" -C "$WORK" .

PUB=~/.config/ecobuilding/backup.pub
if command -v age >/dev/null && [ -f "$PUB" ]; then
  age -R "$PUB" -o "$TAR.age" "$TAR" && rm -f "$TAR"
  echo "== encrypted: $TAR.age"
else
  echo "WARN: age or recipient key missing — archive left UNENCRYPTED at $TAR"
  echo "      (setup: age-keygen -o backup.key; keep .key OFF the VM; put the"
  echo "       public line in $PUB)"
fi

# Retention: keep the 14 most recent archives.
ls -1t "$DIR"/ecobuilding-*.tar.gz* 2>/dev/null | tail -n +15 | xargs -r rm -f
echo "== done. Archives:"; ls -lh "$DIR" | tail -5
